name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        mongodb-version: ['6.0', '8.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Create .env file
        run: |
          touch .env
          echo "${{ secrets.API }}" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright (optional, if using browser tests)
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npm test

  deploy:
    name: Deploy
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
